source "https://rubygems.org"
gem "jekyll"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "jemoji"
gem "jekyll-include-cache"
gem "rake", "12.3.3"
gem "wdm", "~> 0.1.0" if Gem.win_platform?
gem "webrick", "~> 1.7"